version: '3.8'
services:
  web: 
    image: emillie/AmonyCoffeeMIS
    ports: 
      - "8080:80"
    depends_on:
      - database
  
  database:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
  