version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: emillienatalie/amonycoffeemis:latest
    ports: 
      - "8080:80"
    depends_on:
      - database
  
  database:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data