name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-docker-hotspot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push using Docker Compose
      - name: Build and push images using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: deploy to digitalocean
        run: |
          ssh -p ${{ secrets.DROPLET_PASSWORD }} ssh root@143.244.160.153 'docker pull  emillienatalie/amonycoffeemis:latest && docker stop amonycoffeemis && docker rm  amonycoffeemis && docker run -d -p 80:80 --name natalie  emillienatalie/amonycoffeemis:latest'
             