name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
      
    - name: Deploy to DigitalOcean
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh root@143.244.160.153 'docker pull emillienatalie/amonycoffeemis:latest && docker stop amonycoffeemis && docker rm amonycoffeemis && docker run -d -p 80:80 --name natalie emillienatalie/amonycoffeemis:latest'